name: zendesk_helper
description: A Flutter plugin for the Zendesk Chat SDK v2
publish_to: none
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.muljin.zendesk
        pluginClass: ZendeskHelper
      ios:
        pluginClass: ZendeskHelper
